### ISSUE TITLE
Support org readme

### ISSUE THREAD

**Issue by florian-lefebvre** [Atinux/nuxt-typo-readme#2]
Would be great to be able to just type the org name and get the repo (like https://github.com/op-ent). I guess it could be archived. I guess it would be fetched like so: `https://github.com/${org}/.github/blob/main/profile/README.md`

**Comment by Atinux** [comment]
This should be possible, the CDN url is https://raw.githubusercontent.com/op-ent/.github/main/profile/README.md

You can open a PR to add the `pages/[owner]/index.vue` if you want to 😀

**Comment by florian-lefebvre** [comment]
Sure I will do
